import React, { createContext, useContext, useState, useEffect } from 'react';

export const languages = [
  { code: 'en-IN', name: 'English', native: 'English' },
  { code: 'hi-IN', name: 'Hindi', native: 'हिन्दी' },
  { code: 'te-IN', name: 'Telugu', native: 'తెలుగు' },
  { code: 'ta-IN', name: 'Tamil', native: 'தமிழ்' },
  { code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml-IN', name: 'Malayalam', native: 'മലയാളం' },
  { code: 'mr-IN', name: 'Marathi', native: 'मराठी' },
  { code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'bn-IN', name: 'Bengali', native: 'বাংলা' },
  { code: 'pa-IN', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'od-IN', name: 'Odia', native: 'ଓଡ଼ିଆ' },
];

const translations: Record<string, Record<string, string>> = {
  'en-IN': {
    'dashboard': 'Dashboard',
    'predictive_analysis': 'Predictive Analysis',
    'smart_planner': 'Smart Planner',
    'weekly_planner': 'Weekly Planner',
    'satellite_analysis': 'Satellite Analysis',
    'refer_earn': 'Refer & Earn',
    'operations': 'Operations',
    'operations_overview': 'Operations Overview',
    'global_dashboard': 'Global Dashboard',
    'precision_task_planner': 'Precision Task Planner',
    'generate_farm_plan': 'Generate Your Farm Plan',
    'initialize_farm': 'Initialize Your Farm',
    'analysis': 'Analysis',
    'ai_verified': 'AI Verified',
    'download_pdf': 'Download PDF Report',
    'add_to_week_plan': 'Add to Week Plan',
    'edit_parameters': 'Edit Parameters',
    'farm_overview': 'Farm Overview',
    'top_recommendations': 'Top Recommendations — Act Now',
    'crop_recommendations': 'Crop Recommendations',
    'temporal_analysis': 'Temporal Vegetation Analysis',
    'kisaan_ai': 'Kisaan AI Expert',
    'new_chat': 'New Chat',
    'sign_out': 'Sign Out',
    'live_sync': 'Live Sync',
    'local_conditions': 'Local Conditions',
    'temperature': 'Temperature',
    'rainfall': 'Rainfall',
    'wind_speed': 'Wind Speed',
    'monthly_yield': 'Monthly Yield Projection',
    'irrigation_check': 'Irrigation Check',
    'required_today': 'Required Today',
    'not_required': 'Not Required',
    'analyzing_field': 'Analyzing Field Vectors',
    'yield_potential': 'Yield Potential',
    'on_track': 'On Track',
    'weekly_progress': 'Weekly Plan Progress',
    'priority_tasks': 'Priority Tasks',
    'farm_status': 'Farm Status',
    'soil_moisture': 'Soil Moisture',
    'growth_stage': 'Growth Stage',
    'field_size': 'Field Size',
    'labor_available': 'Labor Available',
    'detect_location': 'Detect current location',
    'high_growth_zone': 'High Growth Zone',
    'current_weather': 'Current Weather',
    'intel_recomm': 'Intelligent Recommendations',
    'connecting_satellites': 'Connecting to satellites...',
    'fetching_satellite': 'Fetching multi-spectral satellite data...',
    'dashboard_no_plan_desc': 'Your dashboard is ready, but it needs a farm plan to provide precise operational insights.',
    'detecting_weather_for': 'Detecting weather for',
    'your_area': 'your area',
    'catch_up': 'You have some catch-up to do!',
    'staying_on_top': 'Great job staying on top of tasks!',
    'irrigation_vital': 'Low moisture and no rain forecasted means irrigation is vital today.',
    'irrigation_not_needed': 'Current moisture levels suggest no immediate irrigation is needed.',
    'todays_priorities': "Today's Top Priorities",
    'recent_completed': 'Recent Completed',
    'tasks': 'tasks',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'match': 'Match',
    'farm_status_overview': 'Farm Status Overview',
    'real_time_data': 'Real-time Data',
    'irrigation_urgency': 'Irrigation Urgency',
    'equipment_risk': 'Equipment risk',
    'members': 'Members',
    'critical_deficit': 'Critical deficit',
    'threshold_level': 'Threshold level',
    'optimal_range': 'Optimal range',
    'action_required': 'Action required',
    'monitor_closely': 'Monitor closely',
    'staff_shortage': 'Staff shortage',
    'full_team_active': 'Full team active',
    'maintenance_soon': 'Maintenance due soon',
    'resource_strain': 'Resource strain detected',
    'sub_optimal': 'Sub-optimal capacity',
    'enter_city': 'Enter city...',
    'go': 'Go',
    'could_not_detect_location': 'Could not detect location. Please search manually.',
    'search_history': 'Search history...',
    'recent_chats': 'Recent Chats',
    'no_matches_found': 'No matches found',
    'no_history_yet': 'No history yet',
    'historical_perf_desc': 'Historical performance and future operational trends.',
    'export_csv': 'Export CSV',
    'past_30_days': 'Past 30 Days',
    'regional_comparisons': 'Regional Comparisons',
    'north_sector': 'North Sector',
    'south_valley': 'South Valley',
    'highlands': 'Highlands',
    'efficiency': 'Efficiency',
    'sustainability_report': 'Sustainability Report',
    'sustainability_desc': 'Your optimized AI scheduling has prevented the waste of approximately 14,200 liters of water this quarter.',
    'co2_offset': 'CO2 Offset',
    'fuel_saved': 'Fuel Saved',
    'bio_waste': 'Bio-waste',
    'energy': 'Energy',
    'saved': 'Saved',
    'target_region': 'Target Region',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'analyze_recommend': 'Analyze & Recommend',
    'crop_recomm_desc': 'AI analysis based on geographical metadata',
    'temporal_analysis_desc': 'Compare land health changes across time',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'compute_delta': 'Compute Delta',
    'baseline': 'Baseline',
    'current': 'Current',
    'normal': 'NORMAL',
    'heatmap': 'HEATMAP',
    'ndvi_heatmap_rgb': 'NDVI Heatmap (RGB)',
    'healthy_veg': 'Neon Green: Healthy vegetation',
    'stressed_crops': 'Darker Green: Stressed crops',
    'dry_soil_zones': 'Earth Tones: Dry soil zones',
    'water_bodies': 'Deep Blue: Water bodies',
    'veg_delta_detected': 'Vegetation Delta Detected',
    'loss': 'Loss',
    'health_trajectory': 'Health Trajectory',
    'yield_performance': 'Yield Performance',
    'hydration_water_risk': 'Hydration / Water Risk',
    'alert': 'Alert',
    'interactive_overlay': 'Interactive Overlay Analysis',
    'slide_divider_desc': 'Slide the divider to compare temporal states • Left: Baseline • Right: Current',
    'move_slider_desc': 'Move slider to reveal vegetation delta',
    'health_retained': 'Health Retained',
    'referral_program': 'Referral Program',
    'refer_earn_title': 'Refer & earn credit with shareable link',
    'refer_earn_desc': 'Share FarmCopilot AI with your friends and fellow farmers. When they sign up, you both earn credits for premium features.',
    'unique_link': 'Your Unique Link',
    'copied': 'Copied',
    'copy': 'Copy',
    'share_on_whatsapp': 'Share on WhatsApp',
    'share_link': 'Share Link',
    'share_link_desc': 'Copy and send your link to friends',
    'friend_joins': 'Friend Joins',
    'friend_joins_desc': 'They sign up using your link',
    'earn_credits': 'Earn Credits',
    'earn_credits_desc': 'Credits are added to your wallet',
    'whatsapp_share_text': 'Join FarmCopilot AI using my link and get credits!',
    'credits_system': 'Credits System',
    'how_credits_work': 'How Credits Work',
    'credits_system_desc': 'Use credits to access all AI-powered features. Earn them by referring friends or purchase them directly.',
    'credits_per_referral': 'Credits Per Referral',
    'credits_per_referral_desc': 'When your friend joins FarmCopilot AI using your referral link, you instantly earn 100 credits in your wallet.',
    'credits_per_request': 'Credits Per Request',
    'credits_per_request_desc': 'Each AI feature request — crop advice, satellite analysis, planner generation — costs just 2 credits.',
    'rupee_equals_credit': 'Rupee = Credit',
    'rupee_equals_credit_desc': '1 Indian Rupee (₹1) equals 1 credit. Top up your wallet anytime with secure payments.',
    'credit_summary_title': 'Start for Free — Earn as You Grow!',
    'credit_summary_desc': 'Refer just one friend to earn 100 credits — that\'s 50 AI requests for free! Each feature costs only 2 credits (₹2) per use.',
    'credit_value': '₹1 = 1 Credit',
    'smart_crop_advisor': 'Smart Crop Advisor',
    'crop_advisor_desc': 'Enter your farming location and planting months to get personalised crop recommendations powered by Machine Learning and real historical weather data.',
    'location_season': 'Location & Season',
    'farming_location': 'Farming Location',
    'eg_punjab_india': 'e.g. Punjab, India / Maharashtra / Nairobi, Kenya',
    'growing_months': 'Growing Months',
    'select_all_apply': 'select all that apply',
    'select_all': 'Select All',
    'soil_type': 'Soil Type',
    'field_area_acres': 'Field Area (acres)',
    'predict_crops_plan': 'Predict Best Crops & Irrigation Plan',
    'analyzing_datasets': 'Analyzing Agricultural Datasets',
    'consulting_trends': 'Consulting historical climate trends and soil compatibility models...',
    'prediction_complete': 'Prediction Complete',
    'top_crops_for': 'Top Crops for',
    'avg_temp_unit': 'Avg Temperature (°C)',
    'avg_monthly_rain': 'Avg Monthly Rain (mm)',
    'avg_humidity_unit': 'Avg Humidity (%)',
    'irrigation_advice': 'Irrigation Advice',
    'litres_acre_day': 'Litres / Acre / Day',
    'total_litres_day': 'Total Litres / Day',
    'irrigation_frequency': 'Irrigation Frequency',
    'top_recommendation': 'Top Recommendation',
    'confidence_score': 'Confidence Score',
    'season': 'Season',
    'rank': 'Rank',
    'of': 'of',
    'new_analysis': 'New Analysis',
    'export_report': 'Export Report',
    'features': 'Features',
    'why_ai': 'Why AI?',
    'login': 'Login',
    'next_gen_agri': 'Next Gen Agri-Intelligence',
    'hero_title': 'Empowering Farmers with Predictive Precision.',
    'hero_desc': "Convert soil moisture, weather data, and labor availability into actionable daily plans. FarmCopilot AI isn't just a chatbot; it's your farm's central operating brain.",
    'get_started_today': 'Get Started Today',
    'watch_demo': 'Watch Demo',
    'vision_statement': 'Agriculture feeds the world, yet remains one of the least digitized industries. We are building Farmcopilot AI systems that go beyond knowledge delivery to actively orchestrate agricultural operations, from crop advisory and input optimization to supply chain coordination and market access, in every language that matters.',
    'one_platform_control': 'One Platform, Complete Control',
    'one_platform_desc': 'Digitize your agricultural operations with modular features designed for efficiency and yield maximization.',
    'smart_planner_desc': 'AI-driven task prioritization using labor and weather constraints.',
    'risk_guard': 'Risk Guard',
    'risk_guard_desc': 'Real-time monitoring of environmental risks and crop health.',
    'explore_feature': 'Explore Feature',
    'water_savings': 'Water Savings',
    'active_acres': 'Active Acres',
    'decision_confidence': 'Decision Confidence',
    'yield_density': 'Yield Density',
    'ready_transform_farm': 'Ready to transform your farm?',
    'join_thousands_progressive': 'Join thousands of progressive farmers using AI-driven operations support.',
    'enter_ops_center': 'Enter Operations Center',
    'yield_analysis': 'Yield Analysis',
    'task_planner': 'Task Planner',
    'learn': 'Learn',
    'discussions': 'Discussions',
    'user_guide': 'User Guide',
    'api_docs': 'API Docs',
    'public_dataset': 'Public Dataset',
    'our_team': 'Our Team',
    'contact_us': 'Contact Us',
    'host_research': 'Host a Research',
    'terms_privacy': 'Terms · Privacy Policy',
    '7_day_plan': '7-Day Plan',
    'overview': 'Overview',
    'productivity': 'Productivity',
    'weather': 'Weather',
    'key_insights': 'Key Insights',
    'risks': 'Risks',
    'resources': 'Resources',
    'weekly_planner_desc': 'Your AI-generated 7-day action plan from the Task Planner, with day-by-day progress tracking.',
    'no_plan_saved': 'No Plan Saved Yet',
    'no_plan_desc': 'Go to the Task Planner, run an AI analysis for your crop, then click "Save to Week Planner" to track your 7-day plan here.',
    'clear_plan': 'Clear Plan',
    'tasks_completed': 'All Tasks Completed!',
    'ready_next_cycle': "You've successfully managed your farm for the week. Ready for the next cycle?",
    'plan_next_week': 'Plan Next Week',
    'generating_plan': 'Generating Next Plan...',
    'mark_done': 'Mark Done',
    'done': 'Done',
    'today': 'Today',
    'day': 'Day',
    'saved_on': 'Saved',
    'days_done': 'days done',
    'store': 'Store',
    'store_mode': 'Mode',
    'seller': 'Seller',
    'buyer': 'Buyer',
    'seller_desc': 'List your crops for sale',
    'buyer_desc': 'Browse & buy fresh produce',
    'crop_sell': 'Crop Sell',
    'crop_sell_desc': 'List your harvest for direct sale to buyers across India',
    'crop_marketplace': 'Crop Marketplace',
    'crop_marketplace_desc': 'Browse fresh produce directly from verified farmers',
    'add_listing': 'Add Listing',
    'active_listings': 'Active Listings',
    'total_views': 'Total Views',
    'total_revenue': 'Total Revenue',
    'avg_rating': 'Avg Rating',
    'add_new_crop': 'Add New Crop Listing',
    'add_new_crop_desc': 'Fill in the details to list your crop on the marketplace',
    'upload_crop_image': 'Upload Crop Image',
    'upload_image_hint': 'Click to upload a photo of your crop (JPG, PNG)',
    'crop_name': 'Crop Name',
    'crop_name_placeholder': 'e.g. Organic Basmati Rice',
    'category': 'Category',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'price_per_unit': 'Price / Unit',
    'your_location': 'Your Location',
    'location_placeholder': 'e.g. Ludhiana, Punjab',
    'description': 'Description',
    'description_placeholder': 'Describe your crop quality, growing method, etc.',
    'publish_listing': 'Publish Listing',
    'my_listings': 'My Listings',
    'no_listings_yet': 'No Listings Yet',
    'no_listings_desc': 'Start selling by adding your first crop listing. Reach buyers across India directly.',
    'add_first_crop': 'Add Your First Crop',
    'search_crops': 'Search crops, locations...',
    'all': 'All',
    'total_listings_market': 'Total Listings',
    'categories_available': 'Categories',
    'verified_sellers': 'Verified Sellers',
    'avg_market_rating': 'Avg Rating',
    'price': 'Price',
    'contact_seller': 'Contact',
    'no_crops_found': 'No Crops Found',
    'no_crops_found_desc': 'Try adjusting your search or filter to find what you need.',
    'predicted_price': 'Predicted Market Price',
    'predicting_price': 'Analyzing market data for your crop...',
    'confidence': 'confidence',
    'use_this_price': 'Use This Price'
  },
  'hi-IN': {
    'dashboard': 'डैशबोर्ड',
    'predictive_analysis': 'भविष्य कहनेवाला विश्लेषण',
    'smart_planner': 'स्मार्ट प्लानर',
    'weekly_planner': 'साप्ताहिक योजनाकार',
    'satellite_analysis': 'सैटेलाइट विश्लेषण',
    'refer_earn': 'रेफर करें और कमाएं',
    'operations': 'संचालन',
    'operations_overview': 'संचालन अवलोकन',
    'global_dashboard': 'ग्लोबल डैशबोर्ड',
    'precision_task_planner': 'सटीक कार्य योजनाकार',
    'generate_farm_plan': 'अपना फार्म प्लान बनाएं',
    'initialize_farm': 'अपना फार्म प्रारंभ करें',
    'analysis': 'विश्लेषण',
    'ai_verified': 'AI सत्यापित',
    'download_pdf': 'PDF रिपोर्ट डाउनलोड करें',
    'add_to_week_plan': 'साप्ताहिक योजना में जोड़ें',
    'edit_parameters': 'पैरामीटर संपादित करें',
    'farm_overview': 'फार्म अवलोकन',
    'top_recommendations': 'मुख्य सिफारिशें - अभी कार्य करें',
    'crop_recommendations': 'फसल सिफारिशें',
    'temporal_analysis': 'अस्थायी वनस्पति विश्लेषण',
    'kisaan_ai': 'किसान AI विशेषज्ञ',
    'new_chat': 'नई चैट',
    'sign_out': 'साइन आउट',
    'live_sync': 'लाइव सिंक',
    'local_conditions': 'स्थानीय स्थितियां',
    'temperature': 'तापमान',
    'rainfall': 'वर्षा',
    'wind_speed': 'हवा की गति',
    'monthly_yield': 'मासिक उपज प्रक्षेपण',
    'irrigation_check': 'सिंचाई जांच',
    'required_today': 'आज आवश्यक',
    'not_required': 'आवश्यक नहीं',
    'analyzing_field': 'फील्ड वेक्टर्स का विश्लेषण',
    'yield_potential': 'उपज क्षमता',
    'on_track': 'सही रास्ते पर',
    'weekly_progress': 'साप्ताहिक योजना प्रगति',
    'priority_tasks': 'प्राथमिक कार्य',
    'farm_status': 'फार्म की स्थिति',
    'soil_moisture': 'मिट्टी की नमी',
    'growth_stage': 'विकास की अवस्था',
    'field_size': 'खेत का आकार',
    'labor_available': 'उपलब्ध श्रम',
    'detect_location': 'वर्तमान स्थान का पता लगाएं',
    'high_growth_zone': 'उच्च विकास क्षेत्र',
    'current_weather': 'वर्तमान मौसम',
    'intel_recomm': 'बुद्धिमान सिफारिशें',
    'connecting_satellites': 'उपग्रहों से जुड़ रहा है...',
    'fetching_satellite': 'मल्टी-स्पेक्ट्रल उपग्रह डेटा प्राप्त किया जा रहा है...',
    'dashboard_no_plan_desc': 'आपका डैशबोर्ड तैयार है, लेकिन सटीक परिचालन अंतर्दृष्टि प्रदान करने के लिए इसे एक फार्म योजना की आवश्यकता है।',
    'detecting_weather_for': 'मौसम का पता लगाया जा रहा है',
    'your_area': 'आपके क्षेत्र',
    'catch_up': 'आपको कुछ काम पूरा करने की ज़रूरत है!',
    'staying_on_top': 'कार्यों के प्रति सचेत रहने के लिए बहुत अच्छा काम!',
    'irrigation_vital': 'कम नमी और बारिश का पूर्वानुमान न होने का मतलब है कि आज सिंचाई महत्वपूर्ण है।',
    'irrigation_not_needed': 'वर्तमान नमी का स्तर बताता है कि तत्काल सिंचाई की आवश्यकता नहीं है।',
    'todays_priorities': 'आज की मुख्य प्राथमिकताएं',
    'recent_completed': 'हाल ही में पूरा हुआ',
    'tasks': 'कार्य',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'कम',
    'match': 'मैच',
    'farm_status_overview': 'फार्म की स्थिति का अवलोकन',
    'real_time_data': 'रियल-टाइम डेटा',
    'irrigation_urgency': 'सिंचाई की तात्कालिकता',
    'equipment_risk': 'उपकरण जोखिम',
    'members': 'सदस्य',
    'critical_deficit': 'गंभीर कमी',
    'threshold_level': 'सीमा स्तर',
    'optimal_range': 'इष्टतम सीमा',
    'action_required': 'कार्यवाही आवश्यक',
    'monitor_closely': 'बारीकी से निगरानी करें',
    'staff_shortage': 'कर्मचारियों की कमी',
    'full_team_active': 'पूरी टीम सक्रिय',
    'maintenance_soon': 'रखरखाव की जल्द जरूरत',
    '7_day_plan': '7-दिवसीय योजना',
    'overview': 'अवलोकन',
    'productivity': 'उत्पादकता',
    'weather': 'मौसम',
    'key_insights': 'प्रमुख अंतर्दृष्टि',
    'risks': 'जोखिम',
    'resources': 'संसाधन',
    'weekly_planner_desc': 'टास्क प्लानर से आपकी AI-जनरेटेड 7-दिवसीय कार्य योजना, दिन-प्रतिदिन की प्रगति ट्रैकिंग के साथ।',
    'no_plan_saved': 'अभी तक कोई योजना सहेजी नहीं गई है',
    'no_plan_desc': 'टास्क प्लानर पर जाएं, अपनी फसल के लिए AI विश्लेषण चलाएं, फिर यहां अपनी 7-दिवसीय योजना को ट्रैक करने के लिए "साप्ताहिक योजनाकार में सहेजें" पर क्लिक करें।',
    'clear_plan': 'योजना साफ करें',
    'tasks_completed': 'सभी कार्य पूर्ण!',
    'ready_next_cycle': 'आपने सप्ताह के लिए अपने खेत को सफलतापूर्वक प्रबंधित किया है। अगले चक्र के लिए तैयार हैं?',
    'plan_next_week': 'अगले सप्ताह की योजना बनाएं',
    'generating_plan': 'अगली योजना बन रही है...',
    'mark_done': 'पूर्ण चिह्नित करें',
    'done': 'पूर्ण',
    'today': 'आज',
    'day': 'दिन',
    'saved_on': 'सहेजा गया',
    'days_done': 'दिन पूर्ण',
    'resource_strain': 'संसाधन तनाव का पता चला',
    'sub_optimal': 'उप-इष्टतम क्षमता',
    'enter_city': 'शहर दर्ज करें...',
    'go': 'जाएं',
    'could_not_detect_location': 'स्थान का पता नहीं लगाया जा सका. कृपया मैन्युअल रूप से खोजें।',
    'search_history': 'इतिहास खोजें...',
    'recent_chats': 'हाल की चैट',
    'no_matches_found': 'कोई मेल नहीं मिला',
    'no_history_yet': 'अभी तक कोई इतिहास नहीं',
    'historical_perf_desc': 'ऐतिहासिक प्रदर्शन और भविष्य के परिचालन रुझान।',
    'export_csv': 'CSV निर्यात करें',
    'past_30_days': 'पिछले 30 दिन',
    'regional_comparisons': 'क्षेत्रीय तुलना',
    'north_sector': 'उत्तर क्षेत्र',
    'south_valley': 'दक्षिण घाटी',
    'highlands': 'उच्च प्रदेश',
    'efficiency': 'क्षमता',
    'sustainability_report': 'स्थिरता रिपोर्ट',
    'sustainability_desc': 'आपके अनुकूलित AI शेड्यूलिंग ने इस तिमाही में लगभग 14,200 लीटर पानी की बर्बादी को रोका है।',
    'co2_offset': 'CO2 ऑफसेट',
    'fuel_saved': 'ईंधन की बचत',
    'bio_waste': 'जैव-अपशिष्ट',
    'energy': 'ऊर्जा',
    'saved': 'बचत',
    'target_region': 'लक्ष्य क्षेत्र',
    'latitude': 'अक्षांश',
    'longitude': 'देशांतर',
    'analyze_recommend': 'विश्लेषण और सिफारिश',
    'crop_recomm_desc': 'भौगोलिक मेटाडेटा पर आधारित AI विश्लेषण',
    'temporal_analysis_desc': 'समय के साथ भूमि स्वास्थ्य परिवर्तनों की तुलना करें',
    'from_date': 'प्रारंभ तिथि',
    'to_date': 'अंतिम तिथि',
    'compute_delta': 'डेल्टा की गणना करें',
    'baseline': 'आधार रेखा',
    'current': 'वर्तमान',
    'normal': 'सामान्य',
    'heatmap': 'हीटमैप',
    'ndvi_heatmap_rgb': 'NDVI हीटमैप (RGB)',
    'healthy_veg': 'नियोन हरा: स्वस्थ वनस्पति',
    'stressed_crops': 'गहरा हरा: तनावग्रस्त फसलें',
    'dry_soil_zones': 'मिट्टी के रंग: शुष्क मिट्टी क्षेत्र',
    'water_bodies': 'गहरा नीला: जल निकाय',
    'veg_delta_detected': 'वनस्पति डेल्टा का पता चला',
    'loss': 'नुकसान',
    'health_trajectory': 'स्वास्थ्य प्रक्षेपवक्र',
    'yield_performance': 'उपज प्रदर्शन',
    'hydration_water_risk': 'जलयोजन / जल जोखिम',
    'alert': 'सतर्क',
    'interactive_overlay': 'इंटरएक्टिव ओवरले विश्लेषण',
    'slide_divider_desc': 'सामयिक स्थितियों की तुलना करने के लिए स्लाइडर को खिसकाएं • बायां: आधार रेखा • दायां: वर्तमान',
    'move_slider_desc': 'वनस्पति डेल्टा देखने के लिए स्लाइडर को घुमाएं',
    'health_retained': 'स्वास्थ्य बरकरार',
    'referral_program': 'रेफरल कार्यक्रम',
    'refer_earn_title': 'साझा करने योग्य लिंक के साथ क्रेडिट रेफर करें और कमाएं',
    'refer_earn_desc': 'अपने दोस्तों और साथी किसानों के साथ फार्मकोपायलट एआई साझा करें। जब वे साइन अप करते हैं, तो आप दोनों प्रीमियम सुविधाओं के लिए क्रेडिट अर्जित करते हैं।',
    'unique_link': 'आपका अनूठा लिंक',
    'copied': 'कॉपी किया गया',
    'copy': 'कॉपी करें',
    'share_on_whatsapp': 'व्हाट्सएप पर शेयर करें',
    'share_link': 'लिंक साझा करें',
    'share_link_desc': 'अपना लिंक कॉपी करें और दोस्तों को भेजें',
    'friend_joins': 'मित्र जुड़ता है',
    'friend_joins_desc': 'वे आपके लिंक का उपयोग करके साइन अप करते हैं',
    'earn_credits': 'क्रेडिट कमाएं',
    'earn_credits_desc': 'क्रेडिट आपके वॉलेट में जोड़ दिए जाते हैं',
    'whatsapp_share_text': 'मेरे लिंक का उपयोग करके फार्मकोपायलट एआई में शामिल हों और क्रेडिट प्राप्त करें!',
    'credits_system': 'क्रेडिट सिस्टम',
    'how_credits_work': 'क्रेडिट कैसे काम करते हैं',
    'credits_system_desc': 'सभी AI-संचालित सुविधाओं तक पहुंचने के लिए क्रेडिट का उपयोग करें। दोस्तों को रेफर करके कमाएं या सीधे खरीदें।',
    'credits_per_referral': 'प्रति रेफरल क्रेडिट',
    'credits_per_referral_desc': 'जब आपका दोस्त आपके रेफरल लिंक का उपयोग करके फार्मकोपायलट एआई में शामिल होता है, तो आपको तुरंत 100 क्रेडिट मिलते हैं।',
    'credits_per_request': 'प्रति अनुरोध क्रेडिट',
    'credits_per_request_desc': 'प्रत्येक AI सुविधा अनुरोध — फसल सलाह, सैटेलाइट विश्लेषण, प्लानर — की लागत केवल 2 क्रेडिट है।',
    'rupee_equals_credit': 'रुपया = क्रेडिट',
    'rupee_equals_credit_desc': '1 भारतीय रुपया (₹1) = 1 क्रेडिट। सुरक्षित भुगतान के साथ कभी भी अपना वॉलेट रिचार्ज करें।',
    'credit_summary_title': 'मुफ़्त में शुरू करें — जितना रेफर करें उतना कमाएं!',
    'credit_summary_desc': 'एक दोस्त को रेफर करें और 100 क्रेडिट कमाएं — यानी 50 AI अनुरोध मुफ़्त! प्रत्येक सुविधा की लागत केवल 2 क्रेडिट (₹2) प्रति उपयोग है।',
    'credit_value': '₹1 = 1 क्रेडिट',
    'smart_crop_advisor': 'स्मार्ट फसल सलाहकार',
    'crop_advisor_desc': 'मशीन लर्निंग और वास्तविक ऐतिहासिक मौसम डेटा द्वारा संचालित व्यक्तिगत फसल सिफारिशें प्राप्त करने के लिए अपना खेती स्थान और रोपण महीने दर्ज करें।',
    'location_season': 'स्थान और मौसम',
    'farming_location': 'खेती का स्थान',
    'eg_punjab_india': 'जैसे पंजाब, भारत / महाराष्ट्र / नैरोबी, केन्या',
    'growing_months': 'बढ़ते महीने',
    'select_all_apply': 'लागू होने वाले सभी का चयन करें',
    'select_all': 'सभी चुनें',
    'soil_type': 'मिट्टी का प्रकार',
    'field_area_acres': 'क्षेत्रफल (एकड़)',
    'predict_crops_plan': 'सर्वोत्तम फसलों और सिंचाई योजना की भविष्यवाणी करें',
    'analyzing_datasets': 'कृषि डेटासेट का विश्लेषण',
    'consulting_trends': 'ऐतिहासिक जलवायु रुझानों और मिट्टी अनुकूलता मॉडल से परामर्श...',
    'prediction_complete': 'भविष्यवाणी पूरी हुई',
    'top_crops_for': 'के लिए शीर्ष फसलें',
    'avg_temp_unit': 'औसत तापमान (°C)',
    'avg_monthly_rain': 'औसत मासिक वर्षा (mm)',
    'avg_humidity_unit': 'औसत आर्द्रता (%)',
    'irrigation_advice': 'सिंचाई सलाह',
    'litres_acre_day': 'लीटर / एकड़ / दिन',
    'total_litres_day': 'कुल लीटर / दिन',
    'irrigation_frequency': 'सिंचाई की आवृत्ति',
    'top_recommendation': 'शीर्ष सिफारिश',
    'confidence_score': 'विश्वास स्कोर',
    'season': 'सीजन',
    'rank': 'रैंक',
    'of': 'का',
    'new_analysis': 'नया विश्लेषण',
    'export_report': 'रिपोर्ट निर्यात करें',
    'features': 'विशेषताएं',
    'why_ai': 'एआई क्यों?',
    'login': 'लॉगिन',
    'next_gen_agri': 'अगली पीढ़ी की कृषि-बुद्धि',
    'hero_title': 'भविष्य कहनेवाला परिशुद्धता के साथ किसानों को सशक्त बनाना।',
    'hero_desc': 'मिट्टी की नमी, मौसम डेटा और श्रम उपलब्धता को कार्रवाई योग्य दैनिक योजनाओं में बदलें। फार्मकोपायलट एआई सिर्फ एक चैटबॉट नहीं है; यह आपके खेत का केंद्रीय ऑपरेटिंग दिमाग है।',
    'get_started_today': 'आज ही शुरू करें',
    'watch_demo': 'डेमो देखें',
    'vision_statement': 'कृषि दुनिया को खिलाती है, फिर भी यह सबसे कम डिजीटल उद्योगों में से एक बनी हुई है। हम फार्मकोपायलट एआई सिस्टम बना रहे हैं जो फसल सलाह और इनपुट अनुकूलन से लेकर आपूर्ति श्रृंखला समन्वय और बाजार पहुंच तक, हर भाषा में कृषि कार्यों को सक्रिय रूप से व्यवस्थित करने के लिए ज्ञान वितरण से परे जाते हैं।',
    'one_platform_control': 'एक मंच, पूर्ण नियंत्रण',
    'one_platform_desc': 'दक्षता और उपज अधिकतमकरण के लिए डिज़ाइन की गई मॉड्यूलर सुविधाओं के साथ अपने कृषि कार्यों को डिजिटाइज़ करें।',
    'smart_planner_desc': 'श्रम और मौसम की बाधाओं का उपयोग करके एआई-संचालित कार्य प्राथमिकता।',
    'risk_guard': 'रिस्क गार्ड',
    'risk_guard_desc': 'पर्यावरणीय जोखिमों और फसल स्वास्थ्य की वास्तविक समय की निगरानी।',
    'explore_feature': 'सुविधा का अन्वेषण करें',
    'water_savings': 'पानी की बचत',
    'active_acres': 'सक्रिय एकड़',
    'decision_confidence': 'निर्णय का विश्वास',
    'yield_density': 'उपज घनत्व',
    'ready_transform_farm': 'अपने खेत को बदलने के लिए तैयार हैं?',
    'join_thousands_progressive': 'एआई-संचालित संचालन सहायता का उपयोग करने वाले हजारों प्रगतिশীল किसानों में शामिल हों।',
    'enter_ops_center': 'संचालन केंद्र में प्रवेश करें',
    'yield_analysis': 'उपज विश्लेषण',
    'task_planner': 'कार्य योजनाकार',
    'learn': 'सीखें',
    'discussions': 'चर्चा',
    'user_guide': 'उपयोगकर्ता मार्गदर्शिका',
    'api_docs': 'एपीआई दस्तावेज़',
    'public_dataset': 'सार्वजनिक डेटासेट',
    'our_team': 'हमारी टीम',
    'contact_us': 'संपर्क करें',
    'host_research': 'एक शोध की मेजबानी करें',
    'terms_privacy': 'नियम · गोपनीयता नीति',
    'store': 'स्टोर',
    'store_mode': 'मोड',
    'seller': 'विक्रेता',
    'buyer': 'खरीदार',
    'seller_desc': 'अपनी फसल बिक्री के लिए सूचीबद्ध करें',
    'buyer_desc': 'ताज़ी उपज ब्राउज़ करें और खरीदें',
    'crop_sell': 'फसल बिक्री',
    'crop_sell_desc': 'भारत भर के खरीदारों को सीधे अपनी फसल बेचने के लिए सूचीबद्ध करें',
    'crop_marketplace': 'फसल बाज़ार',
    'crop_marketplace_desc': 'सत्यापित किसानों से सीधे ताज़ी उपज ब्राउज़ करें',
    'add_listing': 'सूची जोड़ें',
    'active_listings': 'सक्रिय सूचियां',
    'total_views': 'कुल दृश्य',
    'total_revenue': 'कुल राजस्व',
    'avg_rating': 'औसत रेटिंग',
    'add_new_crop': 'नई फसल सूची जोड़ें',
    'add_new_crop_desc': 'बाज़ार में अपनी फसल सूचीबद्ध करने के लिए विवरण भरें',
    'upload_crop_image': 'फसल की छवि अपलोड करें',
    'upload_image_hint': 'अपनी फसल की फोटो अपलोड करने के लिए क्लिक करें',
    'crop_name': 'फसल का नाम',
    'crop_name_placeholder': 'जैसे जैविक बासमती चावल',
    'category': 'श्रेणी',
    'quantity': 'मात्रा',
    'unit': 'इकाई',
    'price_per_unit': 'मूल्य / इकाई',
    'your_location': 'आपका स्थान',
    'location_placeholder': 'जैसे लुधियाना, पंजाब',
    'description': 'विवरण',
    'description_placeholder': 'अपनी फसल की गुणवत्ता, उगाने की विधि आदि का वर्णन करें',
    'publish_listing': 'सूची प्रकाशित करें',
    'my_listings': 'मेरी सूचियां',
    'no_listings_yet': 'अभी तक कोई सूची नहीं',
    'no_listings_desc': 'अपनी पहली फसल सूची जोड़कर बिक्री शुरू करें। सीधे भारत भर के खरीदारों तक पहुंचें।',
    'add_first_crop': 'अपनी पहली फसल जोड़ें',
    'search_crops': 'फसल, स्थान खोजें...',
    'all': 'सभी',
    'total_listings_market': 'कुल सूचियां',
    'categories_available': 'श्रेणियां',
    'verified_sellers': 'सत्यापित विक्रेता',
    'avg_market_rating': 'औसत रेटिंग',
    'price': 'कीमत',
    'contact_seller': 'संपर्क करें',
    'no_crops_found': 'कोई फसल नहीं मिली',
    'no_crops_found_desc': 'अपनी खोज या फ़िल्टर समायोजित करें।',
    'predicted_price': 'अनुमानित बाज़ार मूल्य',
    'predicting_price': 'आपकी फसल के लिए बाज़ार डेटा का विश्लेषण...',
    'confidence': 'विश्वसनीयता',
    'use_this_price': 'यह मूल्य उपयोग करें'
  },
  'te-IN': {
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'predictive_analysis': 'అంచనా విశ్లేషణ',
    'smart_planner': 'స్మార్ట్ ప్లానర్',
    'weekly_planner': 'వారపు ప్లానర్',
    'satellite_analysis': 'శాటిలైట్ విశ్లేషణ',
    'refer_earn': 'రిఫర్ & ఎర్న్',
    'operations': 'కార్యకలాపాలు',
    'operations_overview': 'కార్యకలాపాల అవలోకనం',
    'global_dashboard': 'గ్లోబల్ డ్యాష్‌బోర్డ్',
    'precision_task_planner': 'ప్రెసిషన్ టాస్క్ ప్లానర్',
    'generate_farm_plan': 'మీ ఫారమ్ ప్లాన్‌ను రూపొందించండి',
    'initialize_farm': 'మీ పొలాన్ని ప్రారంభించండి',
    'analysis': 'విశ్లేషణ',
    'ai_verified': 'AI ధృవీకరించబడింది',
    'download_pdf': 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    'add_to_week_plan': 'వారపు ప్లాన్‌కు జోడించండి',
    'edit_parameters': 'పారామితులను సవరించండి',
    'farm_overview': 'ఫారమ్ అవలోకనం',
    'top_recommendations': 'ముఖ్యమైన సిఫార్సులు - ఇప్పుడే చర్య తీసుకోండి',
    'crop_recommendations': 'పంట సిఫార్సులు',
    'temporal_analysis': 'టెంపోరల్ వెజిటేషన్ అనాలిసిస్',
    'kisaan_ai': 'కిసాన్ AI నిపుణుడు',
    'new_chat': 'కొత్త చాట్',
    'sign_out': 'సైన్ అవుట్',
    'live_sync': 'లైవ్ సింక్',
    'local_conditions': 'స్థానిక పరిస్థితులు',
    'temperature': 'ఉష్ణోగ్రత',
    'rainfall': 'వర్షపాతం',
    'wind_speed': 'గాలి వేగం',
    'monthly_yield': 'నెలవారీ దిగుబడి అంచనా',
    'irrigation_check': 'నీటిపారుదల తనిఖీ',
    'required_today': 'ఈరోజు అవసరం',
    'not_required': 'అవసరం లేదు',
    'analyzing_field': 'ఫీల్డ్ వెక్టర్స్ విశ్లేషిస్తోంది',
    'yield_potential': 'దిగుబడి సామర్థ్యం',
    'on_track': 'సరిగ్గా ఉంది',
    'weekly_progress': 'వారపు ప్లాన్ పురోగతి',
    'priority_tasks': 'ప్రాధాన్య పనులు',
    'farm_status': 'ఫారమ్ స్థితి',
    'soil_moisture': 'నేల తేమ',
    'growth_stage': 'పెరుగుదల దశ',
    'field_size': 'పొలం పరిమాణం',
    'labor_available': 'అందుబాటులో ఉన్న కార్మికులు',
    'detect_location': 'ప్రస్తుత స్థానాన్ని గుర్తించండి',
    'high_growth_zone': 'అత్యధిక పెరుగుదల జోన్',
    'current_weather': 'ప్రస్తుత వాతావరణం',
    'intel_recomm': 'తెలివైన సిఫార్సులు',
    'connecting_satellites': 'శాటిలైట్‌లకు కనెక్ట్ అవుతోంది...',
    'fetching_satellite': 'మల్టీ-స్పెక్ట్రల్ శాటిలైట్ డేటాను పొందుతోంది...'
  },
  'ta-IN': {
    'dashboard': 'டாஷ்போர்டு',
    'predictive_analysis': 'முன்கணிப்பு பகுப்பாய்வு',
    'smart_planner': 'ஸ்மார்ட் பிளானர்',
    'weekly_planner': 'வாராந்திர பிளானர்',
    'satellite_analysis': 'சாட்டிலைட் பகுப்பாய்வு',
    'refer_earn': 'பரிந்துரைத்து சம்பாதிக்கவும்',
    'operations': 'செயல்பாடுகள்',
    'operations_overview': 'செயல்பாடுகளின் கண்ணோட்டம்',
    'global_dashboard': 'உலகளாவிய டாஷ்போர்டு',
    'precision_task_planner': 'துல்லியமான பணி திட்டமிடுபவர்',
    'generate_farm_plan': 'உங்கள் பண்ணை திட்டத்தை உருவாக்கவும்',
    'initialize_farm': 'உங்கள் பண்ணையைத் தொடங்கவும்',
    'analysis': 'பகுப்பாய்வு',
    'ai_verified': 'AI சரிபார்க்கப்பட்டது',
    'download_pdf': 'PDF அறிக்கையை பதிவிறக்கவும்',
    'add_to_week_plan': 'வார திட்டத்தில் சேர்க்கவும்',
    'edit_parameters': 'அள அளவுருக்களைத் திருத்தவும்',
    'farm_overview': 'பண்ணை கண்ணோட்டம்',
    'top_recommendations': 'முக்கிய பரிந்துரைகள் - இப்போதே செயல்படுங்கள்',
    'crop_recommendations': 'பயிர் பரிந்துரைகள்',
    'temporal_analysis': 'தற்காலிக தாவர பகுப்பாய்வு',
    'kisaan_ai': 'கிசான் AI நிபுணர்',
    'new_chat': 'புதிய அரட்டை',
    'sign_out': 'வெளியேறு',
    'live_sync': 'நேரடி ஒத்திசைவு',
    'local_conditions': 'உள்ளூர் நிலைமைகள்',
    'temperature': 'வெப்பநிலை',
    'rainfall': 'மழைப்பொழிவு',
    'wind_speed': 'காற்றின் வேகம்',
    'monthly_yield': 'மாதாந்திர மகசூல் கணிப்பு',
    'irrigation_check': 'நீர்ப்பாசன சோதனை',
    'required_today': 'இன்று தேவை',
    'not_required': 'தேவையில்லை',
    'analyzing_field': 'புல திசையன்களை பகுப்பாய்வு செய்தல்',
    'yield_potential': 'மகசூல் திறன்',
    'on_track': 'சரியான பாதையில்',
    'weekly_progress': 'வாராந்திர திட்ட முன்னேற்றம்',
    'priority_tasks': 'முன்னுரிமை பணிகள்',
    'farm_status': 'பண்ணை நிலை',
    'soil_moisture': 'மண் ஈரப்பதம்',
    'growth_stage': 'வளர்ச்சி நிலை',
    'field_size': 'வயல் அளவு',
    'labor_available': 'கிடைக்கக்கூடிய தொழிலாளர்',
    'detect_location': 'தற்போதைய இருப்பிடத்தைக் கண்டறியவும்',
    'high_growth_zone': 'அதிக வளர்ச்சி மண்டலம்',
    'current_weather': 'தற்போதைய வானிலை',
    'intel_recomm': 'அறிவுமிக்க பரிந்துரைகள்',
    'connecting_satellites': 'சாட்டிலைட்களுடன் இணைகிறது...',
    'fetching_satellite': 'சாட்டிலைட் தரவுகளைப் பெறுகிறது...'
  },
  'kn-IN': {
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'predictive_analysis': 'ಮುನ್ಸೂಚನೆಯ ವಿಶ್ಲೇಷಣೆ',
    'smart_planner': 'ಸ್ಮಾರ್ಟ್ ಪ್ಲಾನರ್',
    'weekly_planner': 'ಸಾಪ್ತಾಹಿಕ ಪ್ಲಾನರ್',
    'satellite_analysis': 'ಸ್ಯಾಟಲೈಟ್ ವಿಶ್ಲೇಷಣೆ',
    'refer_earn': 'ರೆಫರ್ ಮಾಡಿ ಮತ್ತು ಗಳಿಸಿ',
    'operations': 'ಕಾರ್ಯಾಚರಣೆಗಳು',
    'operations_overview': 'ಕಾರ್ಯಾಚರಣೆಗಳ ಅವಲೋಕನ',
    'global_dashboard': 'ಜಾಗತಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'precision_task_planner': 'ನಿಖರ ಕಾರ್ಯ ಯೋಜಕ',
    'generate_farm_plan': 'ನಿಮ್ಮ ಫಾರಂ ಯೋಜನೆಯನ್ನು ರೂಪಿಸಿ',
    'initialize_farm': 'ನಿಮ್ಮ ಫಾರಂ ಪ್ರಾರಂಭಿಸಿ',
    'analysis': 'ವಿಶ್ಲೇಷಣೆ',
    'ai_verified': 'AI ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'download_pdf': 'PDF ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'add_to_week_plan': 'ವಾರದ ಯೋಜನೆಗೆ ಸೇರಿಸಿ',
    'edit_parameters': 'ನಿಯತಾಂಕಗಳನ್ನು ತಿದ್ದುಪಡಿ ಮಾಡಿ',
    'farm_overview': 'ಫಾರಂ ಅವಲೋಕನ',
    'top_recommendations': 'ಪ್ರಮುಖ ಶಿಫಾರಸುಗಳು - ಈಗಲೇ ಕಾರ್ಯಪ್ರವೃತ್ತರಾಗಿ',
    'crop_recommendations': 'ಬೆಳೆ ಶಿಫಾರಸುಗಳು',
    'temporal_analysis': 'ಸಸ್ಯವರ್ಗದ ವಿಶ್ಲೇಷಣೆ',
    'kisaan_ai': 'ಕಿಸಾನ್ AI ತಜ್ಞ',
    'new_chat': 'ಹೊಸ ಚಾಟ್',
    'sign_out': 'ಸೈನ್ ಔಟ್',
    'live_sync': 'ಲೈವ್ ಸಿಂಕ್',
    'local_conditions': 'ಸ್ಥಳೀಯ ಪರಿಸ್ಥಿತಿಗಳು',
    'temperature': 'ತಾಪಮಾನ',
    'rainfall': 'ಮಳೆ',
    'wind_speed': 'ಗಾಳಿಯ ವೇಗ',
    'monthly_yield': 'ಮಾಸಿಕ ಇಳುವರಿ ಅಂದಾಜು',
    'irrigation_check': 'ನೀರಾವರಿ ತಪಾಸಣೆ',
    'required_today': 'ಇಂದು ಅಗತ್ಯವಿದೆ',
    'not_required': 'ಅಗತ್ಯವಿಲ್ಲ',
    'analyzing_field': 'ಕ್ಷೇತ್ರದ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ',
    'yield_potential': 'ಇಳುವರಿ ಸಾಮರ್ಥ್ಯ',
    'on_track': 'ಸರಿಯಾದ ಹಾದಿಯಲ್ಲಿ',
    'weekly_progress': 'ವಾರದ ಯೋಜನೆ ಪ್ರಗತಿ',
    'priority_tasks': 'ಆದ್ಯತೆಯ ಕೆಲಸಗಳು',
    'farm_status': 'ಫಾರಂ ಸ್ಥಿತಿ',
    'soil_moisture': 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    'growth_stage': 'ಬೆಳವಣಿಗೆಯ ಹಂತ',
    'field_size': 'ಹೊಲದ ಗಾತ್ರ',
    'labor_available': 'ಲಭ್ಯವಿರುವ ಕಾರ್ಮಿಕರು',
    'detect_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಿ',
    'high_growth_zone': 'ಹೆಚ್ಚಿನ ಬೆಳವಣಿಗೆಯ ವಲಯ',
    'current_weather': 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    'intel_recomm': 'ಬುದ್ಧಿವಂತ ಶಿಫಾರಸುಗಳು',
    'connecting_satellites': 'ಉಪಗ್ರಹಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    'fetching_satellite': 'ಉಪಗ್ರಹ ಡೇಟಾವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...'
  },
  'ml-IN': {
    'dashboard': 'ഡാഷ്‌ബോർഡ്',
    'predictive_analysis': 'പ്രവചന വിശകലനം',
    'smart_planner': 'സ്മാർട്ട് പ്ലാന്നർ',
    'weekly_planner': 'വീക്ക്‌ലി പ്ലാന്നർ',
    'satellite_analysis': 'സാറ്റലൈറ്റ് അനാലിസിസ്',
    'refer_earn': 'റഫർ & ഏൺ',
    'operations': 'പ്രവർത്തനങ്ങൾ',
    'operations_overview': 'ഓപ്പറേഷൻസ് ഓവർവ്യൂ',
    'global_dashboard': 'ഗ്ലോബൽ ഡാഷ്‌ബോർഡ്',
    'precision_task_planner': 'പ്രിസിഷൻ ടാസ്ക് പ്ലാന്നർ',
    'generate_farm_plan': 'ഫാം പ്ലാൻ തയ്യാറാക്കുക',
    'initialize_farm': 'ഫാം പ്ലാൻ ആരംഭിക്കുക',
    'analysis': 'വിശകലനം',
    'ai_verified': 'AI വെരിഫൈഡ്',
    'download_pdf': 'PDF റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    'add_to_week_plan': 'വീക്ക് പ്ലാനിലേക്ക് ചേർക്കുക',
    'edit_parameters': 'മാറ്റങ്ങൾ വരുത്തുക',
    'farm_overview': 'ഫാം ഓവർവ്യൂ',
    'top_recommendations': 'പ്രധാന നിർദ്ദേശങ്ങൾ - ഇപ്പോൾ നടപ്പിലാക്കുക',
    'crop_recommendations': 'വിള നിർദ്ദേശങ്ങൾ',
    'temporal_analysis': 'വെജിറ്റേഷൻ അനാലിസിസ്',
    'kisaan_ai': 'കിസാൻ AI വിദഗ്ധൻ',
    'new_chat': 'പുതിയ ചാറ്റ്',
    'sign_out': 'സൈൻ ഔട്ട്',
    'live_sync': 'ലൈവ് സിങ്ക്',
    'local_conditions': 'പ്രാദേശിക സാഹചര്യങ്ങൾ',
    'temperature': 'താപനില',
    'rainfall': 'മഴ',
    'wind_speed': 'കാറ്റിന്റെ വേഗത',
    'monthly_yield': 'പ്രതീക്ഷിക്കുന്ന വിളവ്',
    'irrigation_check': 'ജലസേചന പരിശോധന',
    'required_today': 'ഇന്ന് ആവശ്യമാണ്',
    'not_required': 'ആവശ്യമില്ല',
    'analyzing_field': 'ഫീൽഡ് വെക്റ്ററുകൾ വിശകലനം ചെയ്യുന്നു',
    'yield_potential': 'വിളവ് സാധ്യത',
    'on_track': 'കൃത്യമായ പാതയിൽ',
    'weekly_progress': 'വീക്ക്‌ലി പ്ലാൻ പുരോഗതി',
    'priority_tasks': 'പ്രധാന ജോലികൾ',
    'farm_status': 'ഫാം നിലവാരം',
    'soil_moisture': 'മണ്ണിലെ ഈർപ്പം',
    'growth_stage': 'വളർച്ചാ ഘട്ടം',
    'field_size': 'പാടത്തിന്റെ അളവ്',
    'labor_available': 'ലഭ്യമായ തൊഴിലാളികൾ',
    'detect_location': 'സ്ഥലം കണ്ടെത്തുക',
    'high_growth_zone': 'ഹൈ ഗ്രോത്ത് സോൺ',
    'current_weather': 'ഇപ്പോഴത്തെ കാലാവസ്ഥ',
    'intel_recomm': 'ബുദ്ധിപരമായ നിർദ്ദേശങ്ങൾ',
    'connecting_satellites': 'സാറ്റലൈറ്റുകളുമായി ബന്ധപ്പെടുന്നു...',
    'fetching_satellite': 'സാറ്റലൈറ്റ് ഡാറ്റ ശേഖരിക്കുന്നു...'
  },
  'mr-IN': {
    'dashboard': 'डॅशबोर्ड',
    'predictive_analysis': 'अनुमानित विश्लेषण',
    'smart_planner': 'स्मार्ट प्लॅनर',
    'weekly_planner': 'साप्ताहिक प्लॅनर',
    'satellite_analysis': 'सॅटेलाईट विश्लेषण',
    'refer_earn': 'रेफर करा आणि कमवा',
    'operations': 'ऑपरेशन्स',
    'operations_overview': 'ऑपरेशन्स विहंगावलोकन',
    'global_dashboard': 'ग्लोबल डॅशबोर्ड',
    'precision_task_planner': 'प्रिसिजन टास्क प्लॅनर',
    'generate_farm_plan': 'तुमचा फार्म प्लॅन तयार करा',
    'initialize_farm': 'तुमचा फार्म सुरू करा',
    'analysis': 'विश्लेषण',
    'ai_verified': 'AI सत्यापित',
    'download_pdf': 'PDF रिपोर्ट डाउनलोड करा',
    'add_to_week_plan': 'साप्ताहिक प्लॅन मध्ये जोडा',
    'edit_parameters': 'परिमाणे संपादित करा',
    'farm_overview': 'फार्म विहंगावलोकन',
    'top_recommendations': 'मुख्य शिफारसी - आत्ताच कृती करा',
    'crop_recommendations': 'पिकांच्या शिफारसी',
    'temporal_analysis': 'वनस्पती विश्लेषण',
    'kisaan_ai': 'किसान AI तज्ञ',
    'new_chat': 'नवीन चॅट',
    'sign_out': 'साइन आउट',
    'live_sync': 'लाईव्ह सिंक',
    'local_conditions': 'स्थानिक परिस्थिती',
    'temperature': 'तापमान',
    'rainfall': 'पाऊस',
    'wind_speed': 'वाऱ्याचा वेग',
    'monthly_yield': 'मासिक उत्पन्न अंदाज',
    'irrigation_check': 'सिंचन तपासणी',
    'required_today': 'आज आवश्यक',
    'not_required': 'आवश्यक नाही',
    'analyzing_field': 'फील्ड वेक्टर्सचे विश्लेषण करत आहे',
    'yield_potential': 'उत्पादन क्षमता',
    'on_track': 'योग्य मार्गावर',
    'weekly_progress': 'साप्ताहिक प्लॅन प्रगती',
    'priority_tasks': 'अग्रक्रम कार्ये',
    'farm_status': 'फार्म स्थिती',
    'soil_moisture': 'जमिनीतील ओलावा',
    'growth_stage': 'वाढीची अवस्था',
    'field_size': 'शेताचा आकार',
    'labor_available': 'उपलब्ध मजूर',
    'detect_location': 'सध्याचे स्थान शोधा',
    'high_growth_zone': 'उच्च वाढ क्षेत्र',
    'current_weather': 'सध्याचे हवामान',
    'intel_recomm': 'बुद्धिमान शिफारसी',
    'connecting_satellites': 'सॅटेलाईट्सशी जोडत आहे...',
    'fetching_satellite': 'सॅटेलाईट डेटा मिळवत आहे...'
  },
  'gu-IN': {
    'dashboard': 'ડેશબોર્ડ',
    'predictive_analysis': 'અનુમાનિત વિશ્લેષણ',
    'smart_planner': 'સ્માર્ટ પ્લાનર',
    'weekly_planner': 'સાપ્તાહિક પ્લાનર',
    'satellite_analysis': 'સેટેલાઇટ વિશ્લેષણ',
    'refer_earn': 'રેફર કરો અને કમાઓ',
    'operations': 'ઓપરેશન્સ',
    'operations_overview': 'ઓપરેશન્સ ઓવરવ્યૂ',
    'global_dashboard': 'ગ્લોબલ ડેશબોર્ડ',
    'precision_task_planner': 'પ્રિસિઝન ટાસ્ક પ્લાનર',
    'generate_farm_plan': 'તમારો ફાર્મ પ્લાન બનાવો',
    'initialize_farm': 'તમારો ફાર્મ શરૂ કરો',
    'analysis': 'વિશ્લેષણ',
    'ai_verified': 'AI ચકાસાયેલ',
    'download_pdf': 'PDF રિપોર્ટ ડાઉનલોડ કરો',
    'add_to_week_plan': 'સાપ્તાહિક પ્લાનમાં ઉમેરો',
    'edit_parameters': 'પેરામીટર્સ એડિટ કરો',
    'farm_overview': 'ફાર્મ ઓવરવ્યૂ',
    'top_recommendations': 'મુખ્ય ભલામણો - અત્યારે જ અમલ કરો',
    'crop_recommendations': 'પાકની ભલામણો',
    'temporal_analysis': 'વનસ્પતિ વિશ્લેષણ',
    'kisaan_ai': 'કિસાન AI નિષ્ણાત',
    'new_chat': 'નવી ચેટ',
    'sign_out': 'સાઇન આઉટ',
    'live_sync': 'લાઇવ સિંક',
    'local_conditions': 'સ્થાનિક પરિસ્થિતિઓ',
    'temperature': 'તાપમાન',
    'rainfall': 'વરસાદ',
    'wind_speed': 'પવનની ગતિ',
    'monthly_yield': 'માસિક ઉપજ અંદાજ',
    'irrigation_check': 'સિંચાઈ તપાસ',
    'required_today': 'આજે જરૂરી છે',
    'not_required': 'જરૂરી નથી',
    'analyzing_field': 'ફીલ્ડ વેક્ટર્સનું વિશ્લેષણ કરી રહ્યા છીએ',
    'yield_potential': 'ઉપજ ક્ષમતા',
    'on_track': 'યોગ્ય માર્ગ પર',
    'weekly_progress': 'સાપ્તાહિક પ્લાન પ્રગતિ',
    'priority_tasks': 'પ્રાથમિક કાર્યો',
    'farm_status': 'ફાર્મ સ્થિતિ',
    'soil_moisture': 'જમીનની ભેજ',
    'growth_stage': 'વિકાસનો તબક્કો',
    'field_size': 'ખેતરનું કદ',
    'labor_available': 'ઉપલબ્ધ મજૂરો',
    'detect_location': 'વર્તમાન સ્થાન શોધો',
    'high_growth_zone': 'ઉચ્ચ વૃદ્ધિ ક્ષેત્ર',
    'current_weather': 'વર્તમાન હવામાન',
    'intel_recomm': 'બુદ્ધિશાળી ભલામણો',
    'connecting_satellites': 'સેટેલાઇટ્સ સાથે જોડાઈ રહ્યું છે...',
    'fetching_satellite': 'સેટેલાઇટ ડેટા મેળવી રહ્યા છીએ...'
  },
  'bn-IN': {
    'dashboard': 'ড্যাশবোর্ড',
    'predictive_analysis': 'ভবিষ্যদ্বাণীমূলক বিশ্লেষণ',
    'smart_planner': 'স্মার্ট প্ল্যানার',
    'weekly_planner': 'সাপ্তাহিক প্ল্যানার',
    'satellite_analysis': 'স্যাটেলাইট বিশ্লেষণ',
    'refer_earn': 'রেফার করুন এবং আয় করুন',
    'operations': 'অপারেশনস',
    'operations_overview': 'কাজের ওভারভিউ',
    'global_dashboard': 'গ্লোবাল ড্যাশবোর্ড',
    'precision_task_planner': 'প্রিসিশন টাস্ক প্ল্যানার',
    'generate_farm_plan': 'ফার্ম প্ল্যান তৈরি করুন',
    'initialize_farm': 'আপনার ফার্ম শুরু করুন',
    'analysis': 'বিশ্লেষণ',
    'ai_verified': 'AI ভেরিফাইড',
    'download_pdf': 'PDF রিপোর্ট ডাউনলোড করুন',
    'add_to_week_plan': 'সাপ্তাহিক প্ল্যানে যোগ করুন',
    'edit_parameters': 'প্যারামিটার পরিবর্তন করুন',
    'farm_overview': 'ফার্ম ওভারভিউ',
    'top_recommendations': 'মূল সুপারিশ - এখনই পদক্ষেপ নিন',
    'crop_recommendations': 'ফসল সুপারিশ',
    'temporal_analysis': 'উদ্ভিদ বিশ্লেষণ',
    'kisaan_ai': 'কিষাণ AI বিশেষজ্ঞ',
    'new_chat': 'নতুন চ্যাট',
    'sign_out': 'সাইন আউট',
    'live_sync': 'লাইভ সিঙ্ক',
    'local_conditions': 'স্থানীয় পরিস্থিতি',
    'temperature': 'তাপমাত্রা',
    'rainfall': 'বৃষ্টিপাত',
    'wind_speed': 'বাতাসের গতি',
    'monthly_yield': 'মাসিক ফলন পূর্বাভাস',
    'irrigation_check': 'সেচ পরীক্ষা',
    'required_today': 'আজ প্রয়োজন',
    'not_required': 'প্রয়োজন নেই',
    'analyzing_field': 'ফিল্ড ভেক্টর বিশ্লেষণ করা হচ্ছে',
    'yield_potential': 'ফলন সম্ভাবনা',
    'on_track': 'সঠিক পথে',
    'weekly_progress': 'সাপ্তাহিক প্ল্যান অগ্রগতি',
    'priority_tasks': 'অগ্রাধিকার কাজ',
    'farm_status': 'ফার্ম অবস্থা',
    'soil_moisture': 'মাটির আর্দ্রতা',
    'growth_stage': 'বৃদ্ধির পর্যায়',
    'field_size': 'জমির পরিমাণ',
    'labor_available': 'উপলব্ধ শ্রমিক',
    'detect_location': 'বর্তমান অবস্থান খুঁজুন',
    'high_growth_zone': 'উচ্চ ফলন এলাকা',
    'current_weather': 'বর্তমান আবহাওয়া',
    'intel_recomm': 'বুদ্ধিমান সুপারিশ',
    'connecting_satellites': 'স্যাটেলাইটের সাথে সংযোগ করা হচ্ছে...',
    'fetching_satellite': 'স্যাটেলাইট ডেটা সংগ্রহ করা হচ্ছে...'
  },
  'pa-IN': {
    'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'predictive_analysis': 'ਭਵਿੱਖਬਾਣੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'smart_planner': 'ਸਮਾਰਟ ਪਲੈਨਰ',
    'weekly_planner': 'ਹਫਤਾਵਾਰੀ ਯੋਜਨਾਕਾਰ',
    'satellite_analysis': 'ਸੈਟੇਲਾਈਟ ਵਿਸ਼ਲੇਸ਼ਣ',
    'refer_earn': 'ਰੈਫਰ ਕਰੋ ਅਤੇ ਕਮਾਓ',
    'operations': 'ਕਾਰਵਾਈਆਂ',
    'operations_overview': 'ਕਾਰਵਾਈਆਂ ਦੀ ਸਮੀਖਿਆ',
    'global_dashboard': 'ਗਲੋਬਲ ਡੈਸ਼ਬੋਰਡ',
    'precision_task_planner': 'ਪ੍ਰੀਸੀਜ਼ਨ ਟਾਸਕ ਪਲੈਨਰ',
    'generate_farm_plan': 'ਆਪਣਾ ਫਾਰਮ ਪਲਾਨ ਬਣਾਓ',
    'initialize_farm': 'ਆਪਣਾ ਫਾਰਮ ਸ਼ੁਰੂ ਕਰੋ',
    'analysis': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'ai_verified': 'AI ਦੁਆਰਾ ਪ੍ਰਮਾਣਿਤ',
    'download_pdf': 'PDF ਰਿਪੋਰਟ ਡਾਉਨਲੋਡ ਕਰੋ',
    'add_to_week_plan': 'ਹਫਤਾਵਾਰੀ ਪਲਾਨ ਵਿੱਚ ਜੋੜੋ',
    'edit_parameters': 'ਪੈਰਾਮੀਟਰ ਸੋਧੋ',
    'farm_overview': 'ਫਾਰਮ ਸਮੀਖਿਆ',
    'top_recommendations': 'ਮੁੱਖ ਸਿਫਾਰਸ਼ਾਂ - ਹੁਣੇ ਕਾਰਵਾਈ ਕਰੋ',
    'crop_recommendations': 'ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ',
    'temporal_analysis': 'ਬਨਸਪਤੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'kisaan_ai': 'ਕਿਸਾਨ AI ਮਾਹਿਰ',
    'new_chat': 'ਨਵੀਂ ਚੈਟ',
    'sign_out': 'ਸਾਇਨ ਆਉਟ',
    'live_sync': 'ਲਾਈਵ ਸਿੰਕ',
    'local_conditions': 'ਸਥਾਨਕ ਹਾਲਾਤ',
    'temperature': 'ਤਾਪਮਾਨ',
    'rainfall': 'ਭਾਰੀ ਬਾਰਿਸ਼',
    'wind_speed': 'ਹਵਾ ਦੀ ਗਤੀ',
    'monthly_yield': 'ਮਾਸਿਕ ਝਾੜ ਦਾ ਅਨੁਮਾਨ',
    'irrigation_check': 'ਸਿੰਚਾਈ ਦੀ ਜਾਂਚ',
    'required_today': 'ਅੱਜ ਲੋੜੀਂਦਾ ਹੈ',
    'not_required': 'ਲੋੜ ਨਹੀਂ ਹੈ',
    'analyzing_field': 'ਖੇਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',
    'yield_potential': 'ਝਾੜ ਦੀ ਸੰਭਾਵਨਾ',
    'on_track': 'ਸਹੀ ਰਸਤੇ \'ਤੇ',
    'weekly_progress': 'ਹਫਤਾਵਾਰੀ ਪਲਾਨ ਦੀ ਪ੍ਰਗਤੀ',
    'priority_tasks': 'ਪਹਿਲ ਦੇ ਆਧਾਰ \'ਤੇ ਕੰਮ',
    'farm_status': 'ਫਾਰਮ ਦੀ ਸਥਿਤੀ',
    'soil_moisture': 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
    'growth_stage': 'ਵਾਧੇ ਦਾ ਪੜਾਅ',
    'field_size': 'ਖੇਤ ਦਾ ਆਕਾਰ',
    'labor_available': 'ਉਪਲਬਧ ਮਜ਼ਦੂਰ',
    'detect_location': 'ਮੌਜੂਦਾ ਸਥਾਨ ਦਾ ਪਤਾ ਲਗਾਓ',
    'high_growth_zone': 'ਉੱਚ ਵਿਕਾਸ ਖੇਤਰ',
    'current_weather': 'ਮੌਜੂਦਾ ਮੌਸਮ',
    'intel_recomm': 'ਬੁੱਧੀਮਾਨ ਸਿਫਾਰਸ਼ਾਂ',
    'connecting_satellites': 'ਸੈਟੇਲਾਈਟਾਂ ਨਾਲ ਜੁੜ ਰਿਹਾ ਹੈ...',
    'fetching_satellite': 'ਸੈਟੇਲਾਈਟ ਡੇਟਾ ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...'
  },
  'od-IN': {
    'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'predictive_analysis': 'ଭବିଷ୍ୟବାଣୀ ବିଶ୍ଳେଷଣ',
    'smart_planner': 'ସ୍ମାର୍ଟ ପ୍ଲାନର୍',
    'weekly_planner': 'ସାପ୍ତାହିକ ଯୋଜନାକାରୀ',
    'satellite_analysis': 'ସାଟେଲାଇଟ୍ ବିଶ୍ଳେଷଣ',
    'refer_earn': 'ରେଫର୍ କରନ୍ତୁ ଏବଂ ରୋଜଗାର କରନ୍ତୁ',
    'operations': 'କାର୍ଯ୍ୟକଳାପ',
    'operations_overview': 'କାର୍ଯ୍ୟର ସମୀକ୍ଷା',
    'global_dashboard': 'ଗ୍ଲୋବାଲ୍ ଡ୍ୟାସବୋର୍ଡ',
    'precision_task_planner': 'ପ୍ରେସିଜନ ଟାସ୍କ ପ୍ଲାନର୍',
    'generate_farm_plan': 'ଆପଣଙ୍କ ଫାର୍ମ ଯୋଜନା ପ୍ରସ୍ତୁତ କରନ୍ତୁ',
    'initialize_farm': 'ଆପଣଙ୍କ ଫାର୍ମ ଆରମ୍ଭ କରନ୍ତୁ',
    'analysis': 'ବିଶ୍ଳେଷଣ',
    'ai_verified': 'AI ଦ୍ୱାରା ଯାଞ୍ଚ ହୋଇଛି',
    'download_pdf': 'PDF ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    'add_to_week_plan': 'ସାପ୍ତାହିକ ଯୋଜନାରେ ଯୋଡନ୍ତୁ',
    'edit_parameters': 'ପାରାମିଟର ସଂଶୋଧନ କରନ୍ତୁ',
    'farm_overview': 'ଫାର୍ମ ସମୀକ୍ଷା',
    'top_recommendations': 'ମୁଖ୍ୟ ସୁପାରିଶ - ଏବେ କାର୍ଯ୍ୟକାରୀ କରନ୍ତୁ',
    'crop_recommendations': 'ଫସଲ ସୁପାରିଶ',
    'temporal_analysis': 'ଉଦ୍ଭିଦ ବିଶ୍ଳେଷଣ',
    'kisaan_ai': 'କିଷାନ AI ବିଶେଷଜ୍ଞ',
    'new_chat': 'ନୂତନ ଚାଟ୍',
    'sign_out': 'ସାଇନ୍ ଆଉଟ୍',
    'live_sync': 'ଲାଇଭ୍ ସିଙ୍କ୍',
    'local_conditions': 'ସ୍ଥାନୀୟ ସ୍ଥିତି',
    'temperature': 'ତାପମାତ୍ରା',
    'rainfall': 'ବର୍ଷା',
    'wind_speed': 'ପବନର ବେଗ',
    'monthly_yield': 'ମାସିକ ଅମଳ ପୂର୍ବାନୁମାନ',
    'irrigation_check': 'ଜଳସେଚନ ଯାଞ୍ច',
    'required_today': 'ଆଜି ଆବଶ୍ୟକ',
    'not_required': 'ଆବଶ୍ୟକ ନାହିଁ',
    'analyzing_field': 'ଫିଲ୍ଡ ଭେକ୍ଟର ବିଶ୍ଳେଷଣ କରାଯାଉଛି',
    'yield_potential': 'ଅମଳ କ୍ଷମତା',
    'on_track': 'ଠିକ୍ ରାସ୍ତାରେ',
    'weekly_progress': 'ସାପ୍ତାହିକ ଯୋଜନା ଅଗ୍ରଗତି',
    'priority_tasks': 'ପ୍ରାଥମିକ କାର୍ଯ୍ୟ',
    'farm_status': 'ଫାର୍ମ ସ୍ଥିତି',
    'soil_moisture': 'ମାଟିର ଆର୍ଦ୍ରତା',
    'growth_stage': 'ବୃଦ୍ଧି ପର୍ଯ୍ୟାୟ',
    'field_size': 'ଜମିର ଆକାର',
    'labor_available': 'ଉପଲବ୍ଧ ଶ୍ରମିକ',
    'detect_location': 'ବର୍ତ୍ତମାନର ସ୍ଥାନ ଖୋଜନ୍ତು',
    'high_growth_zone': 'ଉଚ୍ଚ ଅମଳ ଅଞ୍ಚଳ',
    'current_weather': 'ବର୍ତ୍ତମାନର ପାଣିପାଗ',
    'intel_recomm': 'ବୁଦ୍ଧିମାନ ସୁପାରିଶ',
    'connecting_satellites': 'ସାଟେଲାଇଟ୍ ସହିତ ସଂଯୋଗ ହେଉଛି...',
    'fetching_satellite': 'ସାଟେଲାଇଟ୍ ତଥ୍ୟ ସଂଗ୍ରହ କରାଯାଉଛି...'
  }
};

interface LanguageContextType {
  language: typeof languages[0];
  setLanguage: (lang: typeof languages[0]) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState(languages[0]);

  useEffect(() => {
    const saved = localStorage.getItem('app_language');
    if (saved) {
      const found = languages.find(l => l.code === saved);
      if (found) setLanguageState(found);
    }
  }, []);

  const setLanguage = (lang: typeof languages[0]) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang.code);
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
  };

  const t = (key: string) => {
    return translations[language.code]?.[key] || translations['en-IN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
